import type { NextPage } from "next";
import React, { useEffect } from "react";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import { useRouter } from "next/router";

import Container from "../components/Container";
import { auth } from "../firebase/firebase";

const Home: NextPage = () => {
  const [user] = useAuthState(auth);
  const router = useRouter();

  useEffect(() => {
    if (user) {
      router.push(`/l/home`);
    } else return;
  }, [user]);

  return (
    <div>
      <Head>
        <title>LinkedIn Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/800px-LinkedIn_logo_initials.png"
        />
      </Head>
      <Container />
    </div>
  );
};

export default Home;
