import { Inter } from "@next/font/google";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { motion } from "framer-motion";

import Feed from "../components/Feed";
import HomeHeader from "../components/HomeHeader";
import ProfileSide from "../components/ProfileSide";
import RightHandSide from "../components/RightHandSide";
import SignIn from "../components/auth/SignIn";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  session: string;
};

export default function Home({ session }: Props) {
  if (!session) return <SignIn />;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>LinkedIn Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/800px-LinkedIn_logo_initials.png"
        />
      </Head>
      <HomeHeader />

      <div className="mx-auto max-h-screen overflow-hidden lg:max-w-6xl mt-8">
        <main className="grid grid-cols-9">
          <ProfileSide />
          <Feed />
          <RightHandSide session={session} />
        </main>
      </div>
    </motion.div>
  );
}

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  return {
    props: {
      session: session,
    },
  };
}
