import { motion } from "framer-motion";
import Head from "next/head";
import React from "react";

import Container from "../Container";

type Props = {};

function SignIn({}: Props) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>LinkedIn Clone Login</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/800px-LinkedIn_logo_initials.png"
        />
      </Head>
      <Container />
    </motion.div>
  );
}

export default SignIn;
